# Generated by Django 2.1.4 on 2018-12-19 18:57

from django.db import migrations, models
import django.db.models.deletion
import rxbackend.rxforeman.foremanapi.ForemanApi


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dependentOn', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabname', models.CharField(max_length=25)),
                ('component_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DemoOnDemandUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DemoOnDemandVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DockerComposeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockercomposeyaml', models.CharField(blank=True, default=0, max_length=1000)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='ForemanHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreman_host_id', models.CharField(default=0, max_length=4)),
                ('status', models.CharField(default=rxbackend.rxforeman.foremanapi.ForemanApi.HostStatus('UNRESOLVED'), max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForemanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('foremanUrl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hostgroup_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=400)),
                ('status', models.CharField(default='UNMANAGED', max_length=255)),
                ('connectioncredentials', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.CredentialsSetting')),
            ],
        ),
        migrations.CreateModel(
            name='InstallHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KVSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('menuoptionname', models.CharField(max_length=255)),
                ('configurationPanel', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system', models.BooleanField(default=True)),
                ('capabilities', models.ManyToManyField(to='rxbackend.Capability')),
            ],
        ),
        migrations.CreateModel(
            name='SaltFormulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=8000)),
                ('status', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaltSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('saltmaster', models.CharField(default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('installed', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Host')),
            ],
        ),
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('handler', models.CharField(max_length=255, null=True)),
                ('module', models.CharField(default=None, max_length=255, null=True)),
                ('SettingsCategory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.SettingsCategory')),
                ('dependentOn', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.StateType')),
            ],
        ),
        migrations.CreateModel(
            name='StateTypeHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField()),
                ('statetype_id', models.IntegerField()),
                ('keyvalList', models.CharField(max_length=4000)),
                ('handlerType', models.CharField(max_length=255)),
                ('handlerCommand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildversion', models.CharField(max_length=150)),
                ('dbStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WizardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.CharField(max_length=200)),
                ('wizard_status', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='statetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxbackend.StateType'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profiletype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.ProfileType'),
        ),
        migrations.AddField(
            model_name='kvsetting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxbackend.SettingsCategory'),
        ),
        migrations.AddField(
            model_name='host',
            name='hostSettings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.SettingsCategory'),
        ),
        migrations.AddField(
            model_name='host',
            name='profileType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.ProfileType'),
        ),
        migrations.AddField(
            model_name='foremanhost',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Host'),
        ),
        migrations.AddField(
            model_name='demoondemandvm',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.ForemanHost'),
        ),
        migrations.AddField(
            model_name='demoondemanduser',
            name='dodenv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.DemoOnDemandVM'),
        ),
        migrations.AddField(
            model_name='credentialssetting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxbackend.SettingsCategory'),
        ),
        migrations.AddField(
            model_name='configurationtab',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Module'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='hosts',
            field=models.ManyToManyField(to='rxbackend.Host'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Profile'),
        ),
        migrations.AddField(
            model_name='capability',
            name='statetypes',
            field=models.ManyToManyField(to='rxbackend.StateType'),
        ),
    ]
