# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hostSettings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.SettingsCategory'),
        ),
        migrations.AddField(
            model_name='statetype',
            name='statetypeSettings',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.SettingsCategory'),
        ),
    ]
