# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetype',
            name='handler',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
