# Generated by Django 2.1.4 on 2019-01-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='NOT_APPLIED', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatableState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='installed',
        ),
        migrations.AddField(
            model_name='simplestate',
            name='base_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.State'),
        ),
        migrations.AddField(
            model_name='repeatablestate',
            name='base_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.State'),
        ),
        migrations.AddField(
            model_name='complexstate',
            name='base_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.State'),
        ),
    ]
