# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoondemandvm',
            name='status',
        ),
        migrations.AddField(
            model_name='foremanhost',
            name='status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
