# Generated by Django 2.1.4 on 2019-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0002_auto_20190121_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetype',
            name='jobtype',
            field=models.CharField(default='SIMPLE_STATE', max_length=255, null=True),
        ),
    ]
