# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import rxbackend.rxforeman.foremanapi.ForemanApi


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0002_auto_20170725_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerComposeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreman_host_id', models.CharField(default=0, max_length=4)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Configuration')),
            ],
        ),
        migrations.AlterField(
            model_name='foremanhost',
            name='status',
            field=models.CharField(default=rxbackend.rxforeman.foremanapi.ForemanApi.HostStatus(b'UNRESOLVED'), max_length=100),
        ),
    ]
