# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0002_statetype_handler'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StateTypeHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField()),
                ('keyvalList', models.CharField(max_length=4000)),
                ('handlerType', models.CharField(max_length=255)),
                ('handlerCommand', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='kvsetting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.SettingsCategory'),
        ),
    ]
