# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0002_auto_20180117_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statetype',
            old_name='statetypeSettings',
            new_name='SettingsCategory',
        ),
    ]
