# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0002_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
