# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0003_auto_20170725_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockercomposeconfiguration',
            name='foreman_host_id',
        ),
        migrations.AddField(
            model_name='dockercomposeconfiguration',
            name='dockercomposeyaml',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
