# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0003_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForemanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('foremanUrl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('hostgroup_id', models.CharField(max_length=5)),
            ],
        ),
    ]
