# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0003_auto_20170816_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetype',
            name='dependentOn',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.StateType'),
        ),
        migrations.AddField(
            model_name='statetypehandler',
            name='statetype_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
