# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0003_auto_20180117_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='system',
            field=models.BooleanField(default=True),
        ),
    ]
