# Generated by Django 2.1.4 on 2019-01-21 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0003_statetype_jobtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestate',
            name='base_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.State'),
        ),
        migrations.AlterField(
            model_name='simplestate',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
