# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0004_auto_20170725_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='hosts',
            field=models.ManyToManyField(to='rxbackend.Host'),
        ),
    ]
