# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0004_auto_20170908_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.SettingsCategory')),
            ],
        ),
        migrations.CreateModel(
            name='InstallHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField()),
            ],
        ),
    ]
