# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0004_foremansettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOnDemandUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Host')),
            ],
        ),
    ]
