# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0004_profiletype_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='profileType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.ProfileType'),
        ),
    ]
