# Generated by Django 2.1.4 on 2019-01-21 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0004_auto_20190121_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplestate',
            name='base_state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.State'),
        ),
    ]
