# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0005_credentialssetting_installhost'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='connectioncredentials',
            field=models.ForeignKey(default=None,null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.CredentialsSetting'),
        ),
    ]
