# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0005_demoondemanduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demoondemanduser',
            old_name='profile',
            new_name='host',
        ),
    ]
