# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0005_configuration_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dockercomposeconfiguration',
            name='dockercomposeyaml',
            field=models.CharField(blank=True, default=0, max_length=1000),
        ),
    ]
