# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0006_auto_20170804_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltsettings',
            name='saltmaster',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
