# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0006_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='dependentOn',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Capability'),
        ),
    ]
