# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0006_auto_20190125_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='RepeatableState',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.RepeatableState'),
        ),
        migrations.AlterField(
            model_name='state',
            name='complex_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.ComplexState'),
        ),
        migrations.AlterField(
            model_name='state',
            name='simple_state',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.SimpleState'),
        ),
    ]
