# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0006_auto_20170720_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoOnDemandVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Host')),
            ],
        ),
        migrations.RemoveField(
            model_name='demoondemanduser',
            name='host',
        ),
        migrations.AddField(
            model_name='demoondemanduser',
            name='dodenv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.DemoOnDemandVM'),
        ),
    ]
