# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0007_saltsettings_saltmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Status',
            field=models.CharField(default=b'UNMANAGED', max_length=255),
        ),
    ]
