# Generated by Django 2.1.4 on 2019-01-29 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0007_auto_20190125_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='RepeatableState',
            new_name='repeatable_state',
        ),
    ]
