# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0007_auto_20170720_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoondemandvm',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Host'),
        ),
    ]
