# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0007_capability_dependenton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capability',
            name='module',
        ),
        migrations.AddField(
            model_name='statetype',
            name='module',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
