# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0008_auto_20180314_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('menuoptionname', models.CharField(max_length=255)),
            ],
        ),
    ]
