# Generated by Django 2.1.4 on 2019-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0008_auto_20190129_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatablestate',
            name='last_successfull_run',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
