# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0009_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='installhost',
            name='host_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
