# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0009_auto_20170804_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('installed', models.BooleanField()),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Capability')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Host')),
            ],
        ),
    ]
