# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0010_auto_20180613_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardstatus',
            name='wizard_status',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
