# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0010_capability_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capabilities', models.ManyToManyField(to='rxbackend.Capability')),
            ],
        ),
    ]
