# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0011_profiletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.ProfileType'),
        ),
    ]
