# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0011_wizardstatus_wizard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingscategory',
            name='prefix',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
