# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0012_auto_20170808_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileType',
            new_name='profiletype',
        ),
    ]
