# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0012_settingscategory_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltFormulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=8000)),
            ],
        ),
    ]
