# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0013_saltformulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltformulas',
            name='status',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
