# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-12 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0014_saltformulas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabname', models.CharField(max_length=25)),
                ('component_tag', models.CharField(max_length=255)),
                ('module', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rxbackend.Module')),
            ],
        ),
    ]
