# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0015_saltaction_saltstatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltstatelog',
            name='start_date',
            field=models.DateField(),
        ),
    ]
