# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0015_configurationtab'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='configurationPanel',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
