# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-25 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0016_auto_20190424_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltstatelog',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
