# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0017_auto_20190425_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltstatelog',
            name='start_time',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
