# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0018_saltstatelog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltstatelog',
            name='changes',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='saltstatelog',
            name='run_num',
            field=models.IntegerField(default=0),
        ),
    ]
