# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0019_auto_20190429_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltstatelog',
            name='changes',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
