# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0021_auto_20190501_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexstate',
            name='last_successfull_run',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='saltstatelog',
            name='complexState',
            field=models.ForeignKey(blank=True, default=None,null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.ComplexState'),
        ),
        migrations.AlterField(
            model_name='saltaction',
            name='test',
            field=models.CharField(max_length=10),
        ),
    ]
