# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-06 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0022_auto_20190506_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplestate',
            name='last_successfull_run',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
