# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0023_simplestate_last_successfull_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statetype',
            old_name='SettingsCategory',
            new_name='state_settings',
        ),
        migrations.AddField(
            model_name='statetype',
            name='connection_credentials',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.CredentialsSetting'),
        ),
    ]
