# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0024_auto_20190516_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statetype',
            name='connection_credentials',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='connection_credentials_category', to='rxbackend.SettingsCategory'),
        ),
    ]
