# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0027_auto_20191010_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='capability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Capability'),
        ),
    ]
