# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0028_auto_20191010_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='statetypePanel',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
