# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-17 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0030_statetype_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiletype',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='host',
            name='profileType',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profiletype',
        ),
        migrations.DeleteModel(
            name='ProfileType',
        ),
    ]
