# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0031_auto_20200217_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Profile'),
            preserve_default=False,
        ),
    ]
