# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0034_auto_20200217_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='configuration',
        ),
        migrations.AddField(
            model_name='configuration',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Profile'),
            preserve_default=False,
        ),
    ]
