# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0035_auto_20200217_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='hosts',
            field=models.ManyToManyField(to='rxbackend.Host'),
        ),
    ]
