# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-04 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0036_configuration_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inherited',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rxbackend.Profile'),
        ),
    ]
