# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rxbackend', '0037_profile_inherited'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_configuration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rxbackend.Configuration'),
        ),
    ]
